name: Composite Git Ref
description: 'Parse Git Ref'

runs:
  using: "composite"
  steps:

    - run: echo ${{ github.ref }}
      shell: bash

    - uses: rishabhgupta/split-by@v1
      id: git-ref
      with:
        string: ${{ github.ref }}
        split-by: '/'

    - run: echo ${{ steps.git-ref.outputs._2 }}
      shell: bash
