name: Composite Git Ref
description: 'Parse Git Ref'

runs:
  using: "composite"
  steps:

    - run: echo ${{ github.ref }}
      shell: bash

    - uses: rishabhgupta/split-by@v1
      id: git-ref
      with:
        string: ${{ github.ref }}
        split-by: '/'

    - run: echo ${{ steps.git-ref.outputs._2 }}
      shell: bash

    - name: Extract PR from GHA Environment
      id: pull-id
      run: echo "::set-output name=pr-id::$(jq --raw-output '.pull_request.number // 0' \"$GITHUB_EVENT_PATH\")"

    - run: |
        echo ${{ env.GITHUB_EVENT_PATH }}
        echo ${{ steps.pull-id.outputs.pr-id }}
