name: Composite Goodbye Action
description: 'Generic Goodbye'

inputs:
  name:
    description: Name
    required: true

runs:
  using: "composite"
  steps:
    - name: Greet Person
      shell: bash
      run: |
        echo "Goodbye, ${{ inputs.name }}"

    # Secrets fail for composite, but work for private
    - name: Pull Secret
      shell: bash
      run: |
        echo "Using ${{ secret.CLUSTER_NAME }}"

